$(document).ready(function () {indexDict['en'] = [{ "title" : "For contributors ", 
"url" : "for-contributors.html", 
"breadcrumbs" : "Bitrise Docs \/ For contributors ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Getting started ", 
"url" : "getting-started.html", 
"breadcrumbs" : "Bitrise Docs \/ Getting started ", 
"snippet" : "Bitrise is powerful and complex - but getting started is easy and intuitive! You can kick off your first build within minutes of signing up. Let’s go over what you need to do to make that happen!...", 
"body" : "Bitrise is powerful and complex - but getting started is easy and intuitive! You can kick off your first build within minutes of signing up. Let’s go over what you need to do to make that happen! " }, 
{ "title" : "Signing up for Bitrise ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-000c8bad-6d7f-0d5d-b401-26d496fba183", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Signing up for Bitrise ", 
"snippet" : "Email GitHub GitLab Bitbucket Signing up with either of the Git service providers means you connect your Bitrise account to your account on that service provider. With a connected account, you can grant Bitrise access to any of your repositories on that account. After signing up, you can connect you...", 
"body" : "Email GitHub GitLab Bitbucket Signing up with either of the Git service providers means you connect your Bitrise account to your account on that service provider. With a connected account, you can grant Bitrise access to any of your repositories on that account. After signing up, you can connect your Bitrise account to all of the three supported Git service providers. For example, after you signed up with GitHub, you can connect your Bitrise account to both your GitLab and Bitbucket accounts, too, and access any repositories you have on those accounts. " }, 
{ "title" : "Adding a new app ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-15a4b450-3823-111b-a88a-98f66ef246cc", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Adding a new app ", 
"snippet" : "Adding a new app to Bitrise means that you connect a Git repository to Bitrise, allowing us to clone the repository and then build it. Add a new app any time by clicking the + symbol on the top menu bar and then selecting Add app from the dropdown menu. As part of the initial configuration process, ...", 
"body" : "Adding a new app to Bitrise means that you connect a Git repository to Bitrise, allowing us to clone the repository and then build it. Add a new app any time by clicking the + symbol on the top menu bar and then selecting Add app from the dropdown menu. As part of the initial configuration process, you: Decide if an app is private or public. Private app data is only available to those who are invited to work on the app. About public apps, read our Public apps guide. Specify the repository: it can be either a GitHub, GitLab or Bitbucket repository, a manual repository URL, or a self-hosted GitLab repository. Register an SSH key: this gives Bitrise access to the repository so we can clone it during the build process. Specify the branch that you want to build. You can change all this later - and anyway, adding a new app takes a couple of minutes so you can always just do the process from scratch. As part of the process, Bitrise will scan and validate your repository and set up an app configuration based on the results of the scan: we can detect the platform type of your app based on the configuration files. If the validation fails, you can set up the app manually. Read the details of the process in our Adding a new app guide. " }, 
{ "title" : "Webhooks and triggers ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-ddaf0b44-cc2e-e0da-0268-aaa5e0a10ba6", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Webhooks and triggers ", 
"snippet" : "You can set up webhooks as part of the process of adding a new app, or at any time later. Webhooks allow Bitrise to communicate with third party services: for example, a Bitrise webhook set up on a GitHub repository allows Bitrise to start a build automatically when code is modified in the repositor...", 
"body" : "You can set up webhooks as part of the process of adding a new app, or at any time later. Webhooks allow Bitrise to communicate with third party services: for example, a Bitrise webhook set up on a GitHub repository allows Bitrise to start a build automatically when code is modified in the repository. Once webhooks are set up, configure when to start builds automatically by defining triggers. You can set: The event which should trigger the build: for example, code push or a pull request. The branch of your repository that can trigger builds: for example, master or dev . This means that you can, for example, set up a trigger that starts a build when a pull request is opened to the master branch. Webhooks are required for triggers to work! Read more about webhooks in our Webhooks guide and about triggers in our Triggering builds guide. " }, 
{ "title" : "Builds and Workflows ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-efd02dd1-4217-aaf4-87c0-debd71494d1c", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Builds and Workflows ", 
"snippet" : "Once you added an app, your first build will be kicked off automatically. To view your builds, go to your Dashboard - which is the first page once you log in to Bitrise -, select the app and click the Builds tab to access your builds. A build is a series of jobs, executed in the order defined in the...", 
"body" : "Once you added an app, your first build will be kicked off automatically. To view your builds, go to your Dashboard - which is the first page once you log in to Bitrise -, select the app and click the Builds tab to access your builds. A build is a series of jobs, executed in the order defined in the app’s Workflow Editor. The jobs are called Steps, which represent blocks of script execution. The Steps can be arranged on the graphical UI of the Workflow Editor and they can do a huge number of things: clone your repository, build your app, run tests, pass values to each other, send notification messages to developers. Read more about Workflows and Steps in our relevant guides: Workflows Steps A build's logs can be viewed on the build’s page: go to the Builds tab and select the build you want. All builds run in clean virtual machines that are discarded after the build is complete. Read more about them in our Virtual machines guide. " }, 
{ "title" : "Teams and Organizations ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-603c18c7-eb0e-7dfc-df86-42313f896cd3", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Teams and Organizations ", 
"snippet" : "Once you set up a new app, you can start inviting team members. If you have a Developer or an Organization plan, you can have unlimited team members! Only members of an app’s team can view a private app, including its logs. For public apps, anyone can view the build logs who has the URL to the build...", 
"body" : "Once you set up a new app, you can start inviting team members. If you have a Developer or an Organization plan, you can have unlimited team members! Only members of an app’s team can view a private app, including its logs. For public apps, anyone can view the build logs who has the URL to the build. You can also create Orgs if you are on one of our Organization plans. Organizations allow you to manage entire teams quickly and effectively. " }, 
{ "title" : "Testing and deploying ", 
"url" : "getting-started.html#UUID-9bb609fc-1b22-e628-165d-46097239fb95_UUID-b4be56a8-29cb-9a91-da5a-2221b0e200ed", 
"breadcrumbs" : "Bitrise Docs \/ Getting started \/ Testing and deploying ", 
"snippet" : "Testing your app and deploying your app are both done with the help of our Steps: we have Steps dedicated to both these functions, based on the platform type. Unit testing, UI testing, and real device testing are all possible on Bitrise. Once your app is tested, built and ready to go, you can quickl...", 
"body" : "Testing your app and deploying your app are both done with the help of our Steps: we have Steps dedicated to both these functions, based on the platform type. Unit testing, UI testing, and real device testing are all possible on Bitrise. Once your app is tested, built and ready to go, you can quickly deploy it to the store of your choice, for example, Google Play or the App Store. Check out Ship, our fast and efficient deployment solution: Deploying with Ship . " }, 
{ "title" : "Infrastructure ", 
"url" : "infrastructure.html", 
"breadcrumbs" : "Bitrise Docs \/ Infrastructure ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Accounts and user management ", 
"url" : "accounts-and-user-management.html", 
"breadcrumbs" : "Bitrise Docs \/ Accounts and user management ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Steps and Workflows ", 
"url" : "steps-and-workflows.html", 
"breadcrumbs" : "Bitrise Docs \/ Steps and Workflows ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Builds ", 
"url" : "builds.html", 
"breadcrumbs" : "Bitrise Docs \/ Builds ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Scheduling builds ", 
"url" : "builds/scheduling-builds.html", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Scheduling builds ", 
"snippet" : "You can schedule your builds to run automatically at a specific time of the week so that you can check your logs when it’s most convenient for you....", 
"body" : "You can schedule your builds to run automatically at a specific time of the week so that you can check your logs when it’s most convenient for you. " }, 
{ "title" : "Scheduling a build ", 
"url" : "builds/scheduling-builds.html#UUID-2a0867b7-fa47-862c-cd31-0e4d05f96471_section-idm4570820012011232576889952983", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Scheduling builds \/ Scheduling a build ", 
"snippet" : "To schedule a build on Bitrise: Go to your Dashboard and click on the project whose build you want to schedule. Click on Start\/Schedule a Build . In the Build configuration pop-up window, toggle the switch to the right to enable Schedule this build feature. Set the hour and minute in the HH\/MM field...", 
"body" : "To schedule a build on Bitrise: Go to your Dashboard and click on the project whose build you want to schedule. Click on Start\/Schedule a Build . In the Build configuration pop-up window, toggle the switch to the right to enable Schedule this build feature. Set the hour and minute in the HH\/MM field. On the timeline, select the day(s) when you want your build to run. Check and fill out the rest of the input fields if necessary. You can schedule your build in the advanced version of the Build configuration window too. Click Schedule Build at the bottom of the pop-up window. Conflicting input Using the Advanced option, you have access to additional options for your build: you can enter a git tag or a commit hash. If, for example, you specify a commit hash, you will notice that the Git Tag option disappears. This ensures that you cannot enter conflicting input values. If you specify a commit hash and a branch where that commit does not exist (for example, master ), Bitrise will find the branch that does have the given commit (for example, testing ) and run a build with that branch. That’s it! Now you can enjoy the comfort of your automated build! " }, 
{ "title" : "Managing a scheduled build ", 
"url" : "builds/scheduling-builds.html#UUID-2a0867b7-fa47-862c-cd31-0e4d05f96471_section-idm4501924705526432576890058372", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Scheduling builds \/ Managing a scheduled build ", 
"snippet" : "If you have one or more regularly scheduled builds, you can: Edit their configuration. Trigger them manually at any time. Temporarily disable them. Permanently delete them....", 
"body" : "If you have one or more regularly scheduled builds, you can: Edit their configuration. Trigger them manually at any time. Temporarily disable them. Permanently delete them. " }, 
{ "title" : "Remote access ", 
"url" : "builds/remote-access.html", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Remote access ", 
"snippet" : "Remote access allows users to connect to their build’s virtual machines via SSH or a screenshare app. A failed build can be rebuilt with remote access enabled to make troubleshooting a lot easier - for example, if the build logs don’t provide enough information about the error. Users who have the Te...", 
"body" : "Remote access allows users to connect to their build’s virtual machines via SSH or a screenshare app. A failed build can be rebuilt with remote access enabled to make troubleshooting a lot easier - for example, if the build logs don’t provide enough information about the error. Users who have the Testers\/QA roles on the app CANNOT use remote access. There are two ways to use remote access on our build machines: SSH : this is available for both Linux\/Docker based and MacOS machines. Screenshare : this is only available for MacOS machines. It uses the VNC system. With either method, you can access the build machine remotely during the build and for 10 minutes after the build is finished. " }, 
{ "title" : "Remote access with SSH ", 
"url" : "builds/remote-access/remote-access-with-ssh.html", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Remote access \/ Remote access with SSH ", 
"snippet" : "To access a Bitrise build machine with SSH, you will need to open a command line interface and the correct command and password: Open the app on Bitrise. Go to the  Builds  tab. Find the build you want to re-run with remote access. Click the  Rebuild with Remote Access  option. Click  Remote Access ...", 
"body" : "To access a Bitrise build machine with SSH, you will need to open a command line interface and the correct command and password: Open the app on Bitrise. Go to the  Builds  tab. Find the build you want to re-run with remote access. Click the  Rebuild with Remote Access  option. Click  Remote Access Instructions . Under the  SSH  option, find and copy the command you will need. Open a command line interface. Run the command found under SSH . ssh -o StrictHostKeyChecking=no vagrant@1.tcp.ngrok.io -p 000000 Copy and paste the password from the Remote Access Instructions page. " }, 
{ "title" : "Finding your files on the VM ", 
"url" : "builds/remote-access/remote-access-with-ssh.html#UUID-7254e1f0-2e1b-3d00-be7e-a09e9099ccc6_section-idm4613673182212832576965162799", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Remote access \/ Remote access with SSH \/ Finding your files on the VM ", 
"snippet" : "Once you successfully logged in to the Bitrise virtual machine that ran your build, you can dive into the files themselves to see what’s happening in real time. After Bitrise finished cloning your app on to the VM, you can always access it at the following location: \/Users\/Vagrant\/git...", 
"body" : "Once you successfully logged in to the Bitrise virtual machine that ran your build, you can dive into the files themselves to see what’s happening in real time. After Bitrise finished cloning your app on to the VM, you can always access it at the following location: \/Users\/Vagrant\/git " }, 
{ "title" : "Remote access with screenshare ", 
"url" : "builds/remote-access/remote-access-with-screenshare.html", 
"breadcrumbs" : "Bitrise Docs \/ Builds \/ Remote access \/ Remote access with screenshare ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Code signing ", 
"url" : "code-signing.html", 
"breadcrumbs" : "Bitrise Docs \/ Code signing ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Testing ", 
"url" : "testing.html", 
"breadcrumbs" : "Bitrise Docs \/ Testing ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Deploying ", 
"url" : "deploying.html", 
"breadcrumbs" : "Bitrise Docs \/ Deploying ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Monitoring ", 
"url" : "monitoring.html", 
"breadcrumbs" : "Bitrise Docs \/ Monitoring ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Bitrise CLI ", 
"url" : "bitrise-cli.html", 
"breadcrumbs" : "Bitrise Docs \/ Bitrise CLI ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Bitrise API ", 
"url" : "bitrise-api.html", 
"breadcrumbs" : "Bitrise Docs \/ Bitrise API ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "API reference ", 
"url" : "bitrise-api/api-reference.html", 
"breadcrumbs" : "Bitrise Docs \/ Bitrise API \/ API reference ", 
"snippet" : "...", 
"body" : "" }
]
$(document).trigger('search.ready');
});